# Generated by Django 4.0.3 on 2022-03-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bdc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radical', models.CharField(max_length=200, null=True)),
                ('bpr', models.CharField(max_length=200, null=True)),
                ('montant', models.FloatField(null=True)),
                ('taux', models.FloatField(null=True)),
                ('ordre', models.CharField(max_length=200, null=True)),
                ('date_emission', models.DateField(auto_now_add=True, null=True)),
                ('dureeE', models.CharField(max_length=200, null=True)),
                ('date_paiment', models.DateField(auto_now_add=True, null=True)),
                ('dureeR', models.CharField(max_length=200, null=True)),
                ('statut', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
