# Generated by Django 4.0.3 on 2022-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdc',
            name='date_emission',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bdc',
            name='date_paiment',
            field=models.DateField(null=True),
        ),
    ]
